version: '3.8'  # Specify the docker-compose version

services:
  academy:
    image: academyimage  # Use your custom image for the academy app
    container_name: academy_container
    environment:
      MYSQL_HOST: mysql_container  # Refer to MySQL service by container name
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: AcademyDB
      MYSQL_USER: root_academy
      MYSQL_PASSWORD: 55tC5vQAvmiyqT
    ports:
      - "8090:8080"  # Map host port 8090 to container's app port 8080


# nota bene !! :- dopo aver fatto compose up collega a academy_network con docker network connect academy_network academy_container


# Se non funziona prova a con command line, ricordati di cambiare i dati 

# docker run -p 8090:8080 --name academy_container --net academy_network -e MYSQL_HOST=mysql_container -e MYSQL_PORT=3306 -e MYSQL_DB_NAME=AcademyDB -e MYSQL_USER=root_academy -e MYSQL_PASSWORD=academypassword academyimage